#!/bin/bash

# if "$SNAP/doom-engine" exists we can expect this to run
# as a content snap within, say, a DOOM map editor.
# On the confinement side the script runs within the parents sandbox.

if [ -d "$SNAP/doom-engine" ]; then
    export SNAP="${SNAP}/doom-engine"
fi

export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl"
export LD_LIBRARY_PATH="$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH
export DOOMWADDIR="${SNAP}/share/games/doom/"

IWAD_FILENAME="$@"
ADDITIONAL_ARGS=""

if [ "$IWAD_FILENAME" == "" ]; then
    IWAD_FILENAME=`zenity \
      --file-selection \
      --title='Select the *.wad to play' \
      --file-filter='WAD file | *.wad *.WAD *.iwad *.IWAD *.pwad *.PWAD'`
fi

IWAD_DIR=$(dirname "${IWAD_FILENAME}")
if [ -d "${IWAD_DIR}" ]; then
    cd "${IWAD_DIR}"
fi

echo "Working directory $PWD"
exec "desktop-launch" "prboom-plus" "${ADDITIONAL_ARGS}" "-iwad" "${IWAD_FILENAME}"
