#!/bin/sh

export DOOMWADDIR="${SNAP}/share/games/doom/"

IWAD_FILENAME="$@"
ADDITIONAL_ARGS=""

if [ "$IWAD_FILENAME" == "" ]; then
    IWAD_FILENAME=`zenity \
      --file-selector \
      --title="Select the *.iwad to play"`
fi

exec "desktop-launch" "prboom-plus" "${ADDITIONAL_ARGS}" "-iwad" "${IWAD_FILENAME}"
